
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point inr0[8] inr0[8] -type PI PI
add mapped point inr0[7] inr0[7] -type PI PI
add mapped point inr0[6] inr0[6] -type PI PI
add mapped point inr0[5] inr0[5] -type PI PI
add mapped point inr0[4] inr0[4] -type PI PI
add mapped point inr0[3] inr0[3] -type PI PI
add mapped point inr0[2] inr0[2] -type PI PI
add mapped point inr0[1] inr0[1] -type PI PI
add mapped point inr0[0] inr0[0] -type PI PI
add mapped point inr1[8] inr1[8] -type PI PI
add mapped point inr1[7] inr1[7] -type PI PI
add mapped point inr1[6] inr1[6] -type PI PI
add mapped point inr1[5] inr1[5] -type PI PI
add mapped point inr1[4] inr1[4] -type PI PI
add mapped point inr1[3] inr1[3] -type PI PI
add mapped point inr1[2] inr1[2] -type PI PI
add mapped point inr1[1] inr1[1] -type PI PI
add mapped point inr1[0] inr1[0] -type PI PI
add mapped point inr2[8] inr2[8] -type PI PI
add mapped point inr2[7] inr2[7] -type PI PI
add mapped point inr2[6] inr2[6] -type PI PI
add mapped point inr2[5] inr2[5] -type PI PI
add mapped point inr2[4] inr2[4] -type PI PI
add mapped point inr2[3] inr2[3] -type PI PI
add mapped point inr2[2] inr2[2] -type PI PI
add mapped point inr2[1] inr2[1] -type PI PI
add mapped point inr2[0] inr2[0] -type PI PI
add mapped point inr3[8] inr3[8] -type PI PI
add mapped point inr3[7] inr3[7] -type PI PI
add mapped point inr3[6] inr3[6] -type PI PI
add mapped point inr3[5] inr3[5] -type PI PI
add mapped point inr3[4] inr3[4] -type PI PI
add mapped point inr3[3] inr3[3] -type PI PI
add mapped point inr3[2] inr3[2] -type PI PI
add mapped point inr3[1] inr3[1] -type PI PI
add mapped point inr3[0] inr3[0] -type PI PI
add mapped point inr4[8] inr4[8] -type PI PI
add mapped point inr4[7] inr4[7] -type PI PI
add mapped point inr4[6] inr4[6] -type PI PI
add mapped point inr4[5] inr4[5] -type PI PI
add mapped point inr4[4] inr4[4] -type PI PI
add mapped point inr4[3] inr4[3] -type PI PI
add mapped point inr4[2] inr4[2] -type PI PI
add mapped point inr4[1] inr4[1] -type PI PI
add mapped point inr4[0] inr4[0] -type PI PI
add mapped point inr5[8] inr5[8] -type PI PI
add mapped point inr5[7] inr5[7] -type PI PI
add mapped point inr5[6] inr5[6] -type PI PI
add mapped point inr5[5] inr5[5] -type PI PI
add mapped point inr5[4] inr5[4] -type PI PI
add mapped point inr5[3] inr5[3] -type PI PI
add mapped point inr5[2] inr5[2] -type PI PI
add mapped point inr5[1] inr5[1] -type PI PI
add mapped point inr5[0] inr5[0] -type PI PI
add mapped point inr6[8] inr6[8] -type PI PI
add mapped point inr6[7] inr6[7] -type PI PI
add mapped point inr6[6] inr6[6] -type PI PI
add mapped point inr6[5] inr6[5] -type PI PI
add mapped point inr6[4] inr6[4] -type PI PI
add mapped point inr6[3] inr6[3] -type PI PI
add mapped point inr6[2] inr6[2] -type PI PI
add mapped point inr6[1] inr6[1] -type PI PI
add mapped point inr6[0] inr6[0] -type PI PI
add mapped point inr7[8] inr7[8] -type PI PI
add mapped point inr7[7] inr7[7] -type PI PI
add mapped point inr7[6] inr7[6] -type PI PI
add mapped point inr7[5] inr7[5] -type PI PI
add mapped point inr7[4] inr7[4] -type PI PI
add mapped point inr7[3] inr7[3] -type PI PI
add mapped point inr7[2] inr7[2] -type PI PI
add mapped point inr7[1] inr7[1] -type PI PI
add mapped point inr7[0] inr7[0] -type PI PI
add mapped point ini0[8] ini0[8] -type PI PI
add mapped point ini0[7] ini0[7] -type PI PI
add mapped point ini0[6] ini0[6] -type PI PI
add mapped point ini0[5] ini0[5] -type PI PI
add mapped point ini0[4] ini0[4] -type PI PI
add mapped point ini0[3] ini0[3] -type PI PI
add mapped point ini0[2] ini0[2] -type PI PI
add mapped point ini0[1] ini0[1] -type PI PI
add mapped point ini0[0] ini0[0] -type PI PI
add mapped point ini1[8] ini1[8] -type PI PI
add mapped point ini1[7] ini1[7] -type PI PI
add mapped point ini1[6] ini1[6] -type PI PI
add mapped point ini1[5] ini1[5] -type PI PI
add mapped point ini1[4] ini1[4] -type PI PI
add mapped point ini1[3] ini1[3] -type PI PI
add mapped point ini1[2] ini1[2] -type PI PI
add mapped point ini1[1] ini1[1] -type PI PI
add mapped point ini1[0] ini1[0] -type PI PI
add mapped point ini2[8] ini2[8] -type PI PI
add mapped point ini2[7] ini2[7] -type PI PI
add mapped point ini2[6] ini2[6] -type PI PI
add mapped point ini2[5] ini2[5] -type PI PI
add mapped point ini2[4] ini2[4] -type PI PI
add mapped point ini2[3] ini2[3] -type PI PI
add mapped point ini2[2] ini2[2] -type PI PI
add mapped point ini2[1] ini2[1] -type PI PI
add mapped point ini2[0] ini2[0] -type PI PI
add mapped point ini3[8] ini3[8] -type PI PI
add mapped point ini3[7] ini3[7] -type PI PI
add mapped point ini3[6] ini3[6] -type PI PI
add mapped point ini3[5] ini3[5] -type PI PI
add mapped point ini3[4] ini3[4] -type PI PI
add mapped point ini3[3] ini3[3] -type PI PI
add mapped point ini3[2] ini3[2] -type PI PI
add mapped point ini3[1] ini3[1] -type PI PI
add mapped point ini3[0] ini3[0] -type PI PI
add mapped point ini4[8] ini4[8] -type PI PI
add mapped point ini4[7] ini4[7] -type PI PI
add mapped point ini4[6] ini4[6] -type PI PI
add mapped point ini4[5] ini4[5] -type PI PI
add mapped point ini4[4] ini4[4] -type PI PI
add mapped point ini4[3] ini4[3] -type PI PI
add mapped point ini4[2] ini4[2] -type PI PI
add mapped point ini4[1] ini4[1] -type PI PI
add mapped point ini4[0] ini4[0] -type PI PI
add mapped point ini5[8] ini5[8] -type PI PI
add mapped point ini5[7] ini5[7] -type PI PI
add mapped point ini5[6] ini5[6] -type PI PI
add mapped point ini5[5] ini5[5] -type PI PI
add mapped point ini5[4] ini5[4] -type PI PI
add mapped point ini5[3] ini5[3] -type PI PI
add mapped point ini5[2] ini5[2] -type PI PI
add mapped point ini5[1] ini5[1] -type PI PI
add mapped point ini5[0] ini5[0] -type PI PI
add mapped point ini6[8] ini6[8] -type PI PI
add mapped point ini6[7] ini6[7] -type PI PI
add mapped point ini6[6] ini6[6] -type PI PI
add mapped point ini6[5] ini6[5] -type PI PI
add mapped point ini6[4] ini6[4] -type PI PI
add mapped point ini6[3] ini6[3] -type PI PI
add mapped point ini6[2] ini6[2] -type PI PI
add mapped point ini6[1] ini6[1] -type PI PI
add mapped point ini6[0] ini6[0] -type PI PI
add mapped point ini7[8] ini7[8] -type PI PI
add mapped point ini7[7] ini7[7] -type PI PI
add mapped point ini7[6] ini7[6] -type PI PI
add mapped point ini7[5] ini7[5] -type PI PI
add mapped point ini7[4] ini7[4] -type PI PI
add mapped point ini7[3] ini7[3] -type PI PI
add mapped point ini7[2] ini7[2] -type PI PI
add mapped point ini7[1] ini7[1] -type PI PI
add mapped point ini7[0] ini7[0] -type PI PI

//output ports
add mapped point outreal0[8] outreal0[8] -type PO PO
add mapped point outreal0[7] outreal0[7] -type PO PO
add mapped point outreal0[6] outreal0[6] -type PO PO
add mapped point outreal0[5] outreal0[5] -type PO PO
add mapped point outreal0[4] outreal0[4] -type PO PO
add mapped point outreal0[3] outreal0[3] -type PO PO
add mapped point outreal0[2] outreal0[2] -type PO PO
add mapped point outreal0[1] outreal0[1] -type PO PO
add mapped point outreal0[0] outreal0[0] -type PO PO
add mapped point outreal1[8] outreal1[8] -type PO PO
add mapped point outreal1[7] outreal1[7] -type PO PO
add mapped point outreal1[6] outreal1[6] -type PO PO
add mapped point outreal1[5] outreal1[5] -type PO PO
add mapped point outreal1[4] outreal1[4] -type PO PO
add mapped point outreal1[3] outreal1[3] -type PO PO
add mapped point outreal1[2] outreal1[2] -type PO PO
add mapped point outreal1[1] outreal1[1] -type PO PO
add mapped point outreal1[0] outreal1[0] -type PO PO
add mapped point outreal2[8] outreal2[8] -type PO PO
add mapped point outreal2[7] outreal2[7] -type PO PO
add mapped point outreal2[6] outreal2[6] -type PO PO
add mapped point outreal2[5] outreal2[5] -type PO PO
add mapped point outreal2[4] outreal2[4] -type PO PO
add mapped point outreal2[3] outreal2[3] -type PO PO
add mapped point outreal2[2] outreal2[2] -type PO PO
add mapped point outreal2[1] outreal2[1] -type PO PO
add mapped point outreal2[0] outreal2[0] -type PO PO
add mapped point outreal3[8] outreal3[8] -type PO PO
add mapped point outreal3[7] outreal3[7] -type PO PO
add mapped point outreal3[6] outreal3[6] -type PO PO
add mapped point outreal3[5] outreal3[5] -type PO PO
add mapped point outreal3[4] outreal3[4] -type PO PO
add mapped point outreal3[3] outreal3[3] -type PO PO
add mapped point outreal3[2] outreal3[2] -type PO PO
add mapped point outreal3[1] outreal3[1] -type PO PO
add mapped point outreal3[0] outreal3[0] -type PO PO
add mapped point outreal4[8] outreal4[8] -type PO PO
add mapped point outreal4[7] outreal4[7] -type PO PO
add mapped point outreal4[6] outreal4[6] -type PO PO
add mapped point outreal4[5] outreal4[5] -type PO PO
add mapped point outreal4[4] outreal4[4] -type PO PO
add mapped point outreal4[3] outreal4[3] -type PO PO
add mapped point outreal4[2] outreal4[2] -type PO PO
add mapped point outreal4[1] outreal4[1] -type PO PO
add mapped point outreal4[0] outreal4[0] -type PO PO
add mapped point outreal5[8] outreal5[8] -type PO PO
add mapped point outreal5[7] outreal5[7] -type PO PO
add mapped point outreal5[6] outreal5[6] -type PO PO
add mapped point outreal5[5] outreal5[5] -type PO PO
add mapped point outreal5[4] outreal5[4] -type PO PO
add mapped point outreal5[3] outreal5[3] -type PO PO
add mapped point outreal5[2] outreal5[2] -type PO PO
add mapped point outreal5[1] outreal5[1] -type PO PO
add mapped point outreal5[0] outreal5[0] -type PO PO
add mapped point outreal6[8] outreal6[8] -type PO PO
add mapped point outreal6[7] outreal6[7] -type PO PO
add mapped point outreal6[6] outreal6[6] -type PO PO
add mapped point outreal6[5] outreal6[5] -type PO PO
add mapped point outreal6[4] outreal6[4] -type PO PO
add mapped point outreal6[3] outreal6[3] -type PO PO
add mapped point outreal6[2] outreal6[2] -type PO PO
add mapped point outreal6[1] outreal6[1] -type PO PO
add mapped point outreal6[0] outreal6[0] -type PO PO
add mapped point outreal7[8] outreal7[8] -type PO PO
add mapped point outreal7[7] outreal7[7] -type PO PO
add mapped point outreal7[6] outreal7[6] -type PO PO
add mapped point outreal7[5] outreal7[5] -type PO PO
add mapped point outreal7[4] outreal7[4] -type PO PO
add mapped point outreal7[3] outreal7[3] -type PO PO
add mapped point outreal7[2] outreal7[2] -type PO PO
add mapped point outreal7[1] outreal7[1] -type PO PO
add mapped point outreal7[0] outreal7[0] -type PO PO
add mapped point outimag0[8] outimag0[8] -type PO PO
add mapped point outimag0[7] outimag0[7] -type PO PO
add mapped point outimag0[6] outimag0[6] -type PO PO
add mapped point outimag0[5] outimag0[5] -type PO PO
add mapped point outimag0[4] outimag0[4] -type PO PO
add mapped point outimag0[3] outimag0[3] -type PO PO
add mapped point outimag0[2] outimag0[2] -type PO PO
add mapped point outimag0[1] outimag0[1] -type PO PO
add mapped point outimag0[0] outimag0[0] -type PO PO
add mapped point outimag1[8] outimag1[8] -type PO PO
add mapped point outimag1[7] outimag1[7] -type PO PO
add mapped point outimag1[6] outimag1[6] -type PO PO
add mapped point outimag1[5] outimag1[5] -type PO PO
add mapped point outimag1[4] outimag1[4] -type PO PO
add mapped point outimag1[3] outimag1[3] -type PO PO
add mapped point outimag1[2] outimag1[2] -type PO PO
add mapped point outimag1[1] outimag1[1] -type PO PO
add mapped point outimag1[0] outimag1[0] -type PO PO
add mapped point outimag2[8] outimag2[8] -type PO PO
add mapped point outimag2[7] outimag2[7] -type PO PO
add mapped point outimag2[6] outimag2[6] -type PO PO
add mapped point outimag2[5] outimag2[5] -type PO PO
add mapped point outimag2[4] outimag2[4] -type PO PO
add mapped point outimag2[3] outimag2[3] -type PO PO
add mapped point outimag2[2] outimag2[2] -type PO PO
add mapped point outimag2[1] outimag2[1] -type PO PO
add mapped point outimag2[0] outimag2[0] -type PO PO
add mapped point outimag3[8] outimag3[8] -type PO PO
add mapped point outimag3[7] outimag3[7] -type PO PO
add mapped point outimag3[6] outimag3[6] -type PO PO
add mapped point outimag3[5] outimag3[5] -type PO PO
add mapped point outimag3[4] outimag3[4] -type PO PO
add mapped point outimag3[3] outimag3[3] -type PO PO
add mapped point outimag3[2] outimag3[2] -type PO PO
add mapped point outimag3[1] outimag3[1] -type PO PO
add mapped point outimag3[0] outimag3[0] -type PO PO
add mapped point outimag4[8] outimag4[8] -type PO PO
add mapped point outimag4[7] outimag4[7] -type PO PO
add mapped point outimag4[6] outimag4[6] -type PO PO
add mapped point outimag4[5] outimag4[5] -type PO PO
add mapped point outimag4[4] outimag4[4] -type PO PO
add mapped point outimag4[3] outimag4[3] -type PO PO
add mapped point outimag4[2] outimag4[2] -type PO PO
add mapped point outimag4[1] outimag4[1] -type PO PO
add mapped point outimag4[0] outimag4[0] -type PO PO
add mapped point outimag5[8] outimag5[8] -type PO PO
add mapped point outimag5[7] outimag5[7] -type PO PO
add mapped point outimag5[6] outimag5[6] -type PO PO
add mapped point outimag5[5] outimag5[5] -type PO PO
add mapped point outimag5[4] outimag5[4] -type PO PO
add mapped point outimag5[3] outimag5[3] -type PO PO
add mapped point outimag5[2] outimag5[2] -type PO PO
add mapped point outimag5[1] outimag5[1] -type PO PO
add mapped point outimag5[0] outimag5[0] -type PO PO
add mapped point outimag6[8] outimag6[8] -type PO PO
add mapped point outimag6[7] outimag6[7] -type PO PO
add mapped point outimag6[6] outimag6[6] -type PO PO
add mapped point outimag6[5] outimag6[5] -type PO PO
add mapped point outimag6[4] outimag6[4] -type PO PO
add mapped point outimag6[3] outimag6[3] -type PO PO
add mapped point outimag6[2] outimag6[2] -type PO PO
add mapped point outimag6[1] outimag6[1] -type PO PO
add mapped point outimag6[0] outimag6[0] -type PO PO
add mapped point outimag7[8] outimag7[8] -type PO PO
add mapped point outimag7[7] outimag7[7] -type PO PO
add mapped point outimag7[6] outimag7[6] -type PO PO
add mapped point outimag7[5] outimag7[5] -type PO PO
add mapped point outimag7[4] outimag7[4] -type PO PO
add mapped point outimag7[3] outimag7[3] -type PO PO
add mapped point outimag7[2] outimag7[2] -type PO PO
add mapped point outimag7[1] outimag7[1] -type PO PO
add mapped point outimag7[0] outimag7[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point outreal7[5]/q outreal7_reg[5]/Q  -type DFF DFF
add mapped point outreal7[5]/q outreal7_reg[5]/QN  -type DFF DFF
add mapped point outreal7[4]/q outreal7_reg[4]/Q  -type DFF DFF
add mapped point outreal7[4]/q outreal7_reg[4]/QN  -type DFF DFF
add mapped point outreal7[2]/q outreal7_reg[2]/Q  -type DFF DFF
add mapped point outreal7[2]/q outreal7_reg[2]/QN  -type DFF DFF
add mapped point outreal7[1]/q outreal7_reg[1]/Q  -type DFF DFF
add mapped point outreal7[1]/q outreal7_reg[1]/QN  -type DFF DFF
add mapped point outreal7[3]/q outreal7_reg[3]/Q  -type DFF DFF
add mapped point outreal7[3]/q outreal7_reg[3]/QN  -type DFF DFF
add mapped point outreal7[0]/q outreal7_reg[0]/Q  -type DFF DFF
add mapped point outreal7[0]/q outreal7_reg[0]/QN  -type DFF DFF
add mapped point outreal5[5]/q outreal5_reg[5]/Q  -type DFF DFF
add mapped point outreal5[5]/q outreal5_reg[5]/QN  -type DFF DFF
add mapped point outreal5[4]/q outreal5_reg[4]/Q  -type DFF DFF
add mapped point outreal5[4]/q outreal5_reg[4]/QN  -type DFF DFF
add mapped point outreal5[2]/q outreal5_reg[2]/Q  -type DFF DFF
add mapped point outreal5[2]/q outreal5_reg[2]/QN  -type DFF DFF
add mapped point outreal5[1]/q outreal5_reg[1]/Q  -type DFF DFF
add mapped point outreal5[1]/q outreal5_reg[1]/QN  -type DFF DFF
add mapped point outreal5[3]/q outreal5_reg[3]/Q  -type DFF DFF
add mapped point outreal5[3]/q outreal5_reg[3]/QN  -type DFF DFF
add mapped point outreal5[0]/q outreal5_reg[0]/Q  -type DFF DFF
add mapped point outreal5[0]/q outreal5_reg[0]/QN  -type DFF DFF
add mapped point outreal3[5]/q outreal3_reg[5]/Q  -type DFF DFF
add mapped point outreal3[5]/q outreal3_reg[5]/QN  -type DFF DFF
add mapped point outreal3[4]/q outreal3_reg[4]/Q  -type DFF DFF
add mapped point outreal3[4]/q outreal3_reg[4]/QN  -type DFF DFF
add mapped point outreal3[2]/q outreal3_reg[2]/Q  -type DFF DFF
add mapped point outreal3[2]/q outreal3_reg[2]/QN  -type DFF DFF
add mapped point outreal3[1]/q outreal3_reg[1]/Q  -type DFF DFF
add mapped point outreal3[1]/q outreal3_reg[1]/QN  -type DFF DFF
add mapped point outreal3[3]/q outreal3_reg[3]/Q  -type DFF DFF
add mapped point outreal3[3]/q outreal3_reg[3]/QN  -type DFF DFF
add mapped point outreal3[0]/q outreal3_reg[0]/Q  -type DFF DFF
add mapped point outreal3[0]/q outreal3_reg[0]/QN  -type DFF DFF
add mapped point outreal1[5]/q outreal1_reg[5]/Q  -type DFF DFF
add mapped point outreal1[5]/q outreal1_reg[5]/QN  -type DFF DFF
add mapped point outreal1[4]/q outreal1_reg[4]/Q  -type DFF DFF
add mapped point outreal1[4]/q outreal1_reg[4]/QN  -type DFF DFF
add mapped point outreal1[2]/q outreal1_reg[2]/Q  -type DFF DFF
add mapped point outreal1[2]/q outreal1_reg[2]/QN  -type DFF DFF
add mapped point outreal1[1]/q outreal1_reg[1]/Q  -type DFF DFF
add mapped point outreal1[1]/q outreal1_reg[1]/QN  -type DFF DFF
add mapped point outreal1[3]/q outreal1_reg[3]/Q  -type DFF DFF
add mapped point outreal1[3]/q outreal1_reg[3]/QN  -type DFF DFF
add mapped point outreal1[0]/q outreal1_reg[0]/Q  -type DFF DFF
add mapped point outreal1[0]/q outreal1_reg[0]/QN  -type DFF DFF
add mapped point outimag7[5]/q outimag7_reg[5]/Q  -type DFF DFF
add mapped point outimag7[5]/q outimag7_reg[5]/QN  -type DFF DFF
add mapped point outimag7[4]/q outimag7_reg[4]/Q  -type DFF DFF
add mapped point outimag7[4]/q outimag7_reg[4]/QN  -type DFF DFF
add mapped point outimag7[2]/q outimag7_reg[2]/Q  -type DFF DFF
add mapped point outimag7[2]/q outimag7_reg[2]/QN  -type DFF DFF
add mapped point outimag7[1]/q outimag7_reg[1]/Q  -type DFF DFF
add mapped point outimag7[1]/q outimag7_reg[1]/QN  -type DFF DFF
add mapped point outimag7[3]/q outimag7_reg[3]/Q  -type DFF DFF
add mapped point outimag7[3]/q outimag7_reg[3]/QN  -type DFF DFF
add mapped point outimag7[0]/q outimag7_reg[0]/Q  -type DFF DFF
add mapped point outimag7[0]/q outimag7_reg[0]/QN  -type DFF DFF
add mapped point outimag5[5]/q outimag5_reg[5]/Q  -type DFF DFF
add mapped point outimag5[5]/q outimag5_reg[5]/QN  -type DFF DFF
add mapped point outimag5[4]/q outimag5_reg[4]/Q  -type DFF DFF
add mapped point outimag5[4]/q outimag5_reg[4]/QN  -type DFF DFF
add mapped point outimag5[2]/q outimag5_reg[2]/Q  -type DFF DFF
add mapped point outimag5[2]/q outimag5_reg[2]/QN  -type DFF DFF
add mapped point outimag5[1]/q outimag5_reg[1]/Q  -type DFF DFF
add mapped point outimag5[1]/q outimag5_reg[1]/QN  -type DFF DFF
add mapped point outimag5[3]/q outimag5_reg[3]/Q  -type DFF DFF
add mapped point outimag5[3]/q outimag5_reg[3]/QN  -type DFF DFF
add mapped point outimag5[0]/q outimag5_reg[0]/Q  -type DFF DFF
add mapped point outimag5[0]/q outimag5_reg[0]/QN  -type DFF DFF
add mapped point outimag3[5]/q outimag3_reg[5]/Q  -type DFF DFF
add mapped point outimag3[5]/q outimag3_reg[5]/QN  -type DFF DFF
add mapped point outimag3[4]/q outimag3_reg[4]/Q  -type DFF DFF
add mapped point outimag3[4]/q outimag3_reg[4]/QN  -type DFF DFF
add mapped point outimag3[2]/q outimag3_reg[2]/Q  -type DFF DFF
add mapped point outimag3[2]/q outimag3_reg[2]/QN  -type DFF DFF
add mapped point outimag3[1]/q outimag3_reg[1]/Q  -type DFF DFF
add mapped point outimag3[1]/q outimag3_reg[1]/QN  -type DFF DFF
add mapped point outimag3[3]/q outimag3_reg[3]/Q  -type DFF DFF
add mapped point outimag3[3]/q outimag3_reg[3]/QN  -type DFF DFF
add mapped point outimag3[0]/q outimag3_reg[0]/Q  -type DFF DFF
add mapped point outimag3[0]/q outimag3_reg[0]/QN  -type DFF DFF
add mapped point outimag1[5]/q outimag1_reg[5]/Q  -type DFF DFF
add mapped point outimag1[5]/q outimag1_reg[5]/QN  -type DFF DFF
add mapped point outimag1[4]/q outimag1_reg[4]/Q  -type DFF DFF
add mapped point outimag1[4]/q outimag1_reg[4]/QN  -type DFF DFF
add mapped point outimag1[2]/q outimag1_reg[2]/Q  -type DFF DFF
add mapped point outimag1[2]/q outimag1_reg[2]/QN  -type DFF DFF
add mapped point outimag1[1]/q outimag1_reg[1]/Q  -type DFF DFF
add mapped point outimag1[1]/q outimag1_reg[1]/QN  -type DFF DFF
add mapped point outimag1[3]/q outimag1_reg[3]/Q  -type DFF DFF
add mapped point outimag1[3]/q outimag1_reg[3]/QN  -type DFF DFF
add mapped point outimag1[0]/q outimag1_reg[0]/Q  -type DFF DFF
add mapped point outimag1[0]/q outimag1_reg[0]/QN  -type DFF DFF
add mapped point outimag0[0]/q outimag0_reg[0]/Q  -type DFF DFF
add mapped point outimag0[0]/q outimag0_reg[0]/QN  -type DFF DFF
add mapped point outimag0[1]/q outimag0_reg[1]/Q  -type DFF DFF
add mapped point outimag0[1]/q outimag0_reg[1]/QN  -type DFF DFF
add mapped point outimag0[2]/q outimag0_reg[2]/Q  -type DFF DFF
add mapped point outimag0[2]/q outimag0_reg[2]/QN  -type DFF DFF
add mapped point outimag0[3]/q outimag0_reg[3]/Q  -type DFF DFF
add mapped point outimag0[3]/q outimag0_reg[3]/QN  -type DFF DFF
add mapped point outimag0[4]/q outimag0_reg[4]/Q  -type DFF DFF
add mapped point outimag0[4]/q outimag0_reg[4]/QN  -type DFF DFF
add mapped point outimag0[5]/q outimag0_reg[5]/Q  -type DFF DFF
add mapped point outimag0[5]/q outimag0_reg[5]/QN  -type DFF DFF
add mapped point outimag2[0]/q outimag2_reg[0]/Q  -type DFF DFF
add mapped point outimag2[0]/q outimag2_reg[0]/QN  -type DFF DFF
add mapped point outimag2[1]/q outimag2_reg[1]/Q  -type DFF DFF
add mapped point outimag2[1]/q outimag2_reg[1]/QN  -type DFF DFF
add mapped point outimag2[2]/q outimag2_reg[2]/Q  -type DFF DFF
add mapped point outimag2[2]/q outimag2_reg[2]/QN  -type DFF DFF
add mapped point outimag2[3]/q outimag2_reg[3]/Q  -type DFF DFF
add mapped point outimag2[3]/q outimag2_reg[3]/QN  -type DFF DFF
add mapped point outimag2[4]/q outimag2_reg[4]/Q  -type DFF DFF
add mapped point outimag2[4]/q outimag2_reg[4]/QN  -type DFF DFF
add mapped point outimag2[5]/q outimag2_reg[5]/Q  -type DFF DFF
add mapped point outimag2[5]/q outimag2_reg[5]/QN  -type DFF DFF
add mapped point outimag4[0]/q outimag4_reg[0]/Q  -type DFF DFF
add mapped point outimag4[0]/q outimag4_reg[0]/QN  -type DFF DFF
add mapped point outimag4[1]/q outimag4_reg[1]/Q  -type DFF DFF
add mapped point outimag4[1]/q outimag4_reg[1]/QN  -type DFF DFF
add mapped point outimag4[2]/q outimag4_reg[2]/Q  -type DFF DFF
add mapped point outimag4[2]/q outimag4_reg[2]/QN  -type DFF DFF
add mapped point outimag4[3]/q outimag4_reg[3]/Q  -type DFF DFF
add mapped point outimag4[3]/q outimag4_reg[3]/QN  -type DFF DFF
add mapped point outimag4[4]/q outimag4_reg[4]/Q  -type DFF DFF
add mapped point outimag4[4]/q outimag4_reg[4]/QN  -type DFF DFF
add mapped point outimag4[5]/q outimag4_reg[5]/Q  -type DFF DFF
add mapped point outimag4[5]/q outimag4_reg[5]/QN  -type DFF DFF
add mapped point outimag6[0]/q outimag6_reg[0]/Q  -type DFF DFF
add mapped point outimag6[0]/q outimag6_reg[0]/QN  -type DFF DFF
add mapped point outimag6[1]/q outimag6_reg[1]/Q  -type DFF DFF
add mapped point outimag6[1]/q outimag6_reg[1]/QN  -type DFF DFF
add mapped point outimag6[2]/q outimag6_reg[2]/Q  -type DFF DFF
add mapped point outimag6[2]/q outimag6_reg[2]/QN  -type DFF DFF
add mapped point outimag6[3]/q outimag6_reg[3]/Q  -type DFF DFF
add mapped point outimag6[3]/q outimag6_reg[3]/QN  -type DFF DFF
add mapped point outimag6[4]/q outimag6_reg[4]/Q  -type DFF DFF
add mapped point outimag6[4]/q outimag6_reg[4]/QN  -type DFF DFF
add mapped point outimag6[5]/q outimag6_reg[5]/Q  -type DFF DFF
add mapped point outimag6[5]/q outimag6_reg[5]/QN  -type DFF DFF
add mapped point outreal0[0]/q outreal0_reg[0]/Q  -type DFF DFF
add mapped point outreal0[0]/q outreal0_reg[0]/QN  -type DFF DFF
add mapped point outreal0[1]/q outreal0_reg[1]/Q  -type DFF DFF
add mapped point outreal0[1]/q outreal0_reg[1]/QN  -type DFF DFF
add mapped point outreal0[2]/q outreal0_reg[2]/Q  -type DFF DFF
add mapped point outreal0[2]/q outreal0_reg[2]/QN  -type DFF DFF
add mapped point outreal0[3]/q outreal0_reg[3]/Q  -type DFF DFF
add mapped point outreal0[3]/q outreal0_reg[3]/QN  -type DFF DFF
add mapped point outreal0[4]/q outreal0_reg[4]/Q  -type DFF DFF
add mapped point outreal0[4]/q outreal0_reg[4]/QN  -type DFF DFF
add mapped point outreal0[5]/q outreal0_reg[5]/Q  -type DFF DFF
add mapped point outreal0[5]/q outreal0_reg[5]/QN  -type DFF DFF
add mapped point outreal2[0]/q outreal2_reg[0]/Q  -type DFF DFF
add mapped point outreal2[0]/q outreal2_reg[0]/QN  -type DFF DFF
add mapped point outreal2[1]/q outreal2_reg[1]/Q  -type DFF DFF
add mapped point outreal2[1]/q outreal2_reg[1]/QN  -type DFF DFF
add mapped point outreal2[2]/q outreal2_reg[2]/Q  -type DFF DFF
add mapped point outreal2[2]/q outreal2_reg[2]/QN  -type DFF DFF
add mapped point outreal2[3]/q outreal2_reg[3]/Q  -type DFF DFF
add mapped point outreal2[3]/q outreal2_reg[3]/QN  -type DFF DFF
add mapped point outreal2[4]/q outreal2_reg[4]/Q  -type DFF DFF
add mapped point outreal2[4]/q outreal2_reg[4]/QN  -type DFF DFF
add mapped point outreal2[5]/q outreal2_reg[5]/Q  -type DFF DFF
add mapped point outreal2[5]/q outreal2_reg[5]/QN  -type DFF DFF
add mapped point outreal4[0]/q outreal4_reg[0]/Q  -type DFF DFF
add mapped point outreal4[0]/q outreal4_reg[0]/QN  -type DFF DFF
add mapped point outreal4[1]/q outreal4_reg[1]/Q  -type DFF DFF
add mapped point outreal4[1]/q outreal4_reg[1]/QN  -type DFF DFF
add mapped point outreal4[2]/q outreal4_reg[2]/Q  -type DFF DFF
add mapped point outreal4[2]/q outreal4_reg[2]/QN  -type DFF DFF
add mapped point outreal4[3]/q outreal4_reg[3]/Q  -type DFF DFF
add mapped point outreal4[3]/q outreal4_reg[3]/QN  -type DFF DFF
add mapped point outreal4[4]/q outreal4_reg[4]/Q  -type DFF DFF
add mapped point outreal4[4]/q outreal4_reg[4]/QN  -type DFF DFF
add mapped point outreal4[5]/q outreal4_reg[5]/Q  -type DFF DFF
add mapped point outreal4[5]/q outreal4_reg[5]/QN  -type DFF DFF
add mapped point outreal6[0]/q outreal6_reg[0]/Q  -type DFF DFF
add mapped point outreal6[0]/q outreal6_reg[0]/QN  -type DFF DFF
add mapped point outreal6[1]/q outreal6_reg[1]/Q  -type DFF DFF
add mapped point outreal6[1]/q outreal6_reg[1]/QN  -type DFF DFF
add mapped point outreal6[2]/q outreal6_reg[2]/Q  -type DFF DFF
add mapped point outreal6[2]/q outreal6_reg[2]/QN  -type DFF DFF
add mapped point outreal6[3]/q outreal6_reg[3]/Q  -type DFF DFF
add mapped point outreal6[3]/q outreal6_reg[3]/QN  -type DFF DFF
add mapped point outreal6[4]/q outreal6_reg[4]/Q  -type DFF DFF
add mapped point outreal6[4]/q outreal6_reg[4]/QN  -type DFF DFF
add mapped point outreal6[5]/q outreal6_reg[5]/Q  -type DFF DFF
add mapped point outreal6[5]/q outreal6_reg[5]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
